<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <IsPackable>false</IsPackable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <OtherFlags>--maxerrors:5000</OtherFlags>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="CoreEnums.proposal.fs" />
    <Compile Include="StringEnums.proposal.fs" />
    <Compile Include="SimpleObjectTypes.proposal.fs" />
    <Compile Include="SimpleAliases.proposal.fs" />
    <Compile Include="SimpleTypes.proposal.fs" />
    <Compile Include="SimpleFunctions.proposal.fs" />
    <Compile Include="SimpleVariables.proposal.fs" />
    <Compile Include="BabylonBindings.generated.fs" />
    <Compile Include="BabylonGltf2Interface.generated.fs" />
    <Compile Include="BabylonLoadersBindings.generated.fs" />
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="Fable.Browser.Dom" />
    <PackageReference Include="Fable.Browser.WebGL" />
  </ItemGroup>
</Project>
