<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <IsPackable>false</IsPackable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <OtherFlags>--maxerrors:5000</OtherFlags>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="_candidateSources/CoreEnums.proposal.fs" />
    <Compile Include="_candidateSources/StringEnums.proposal.fs" />
    <Compile Include="_candidateSources/BabylonBindings.generated.fs" />
    <Compile Include="_candidateSources/BabylonGltf2Interface.generated.fs" />
    <Compile Include="_candidateSources/BabylonLoadersBindings.generated.fs" />
    <Compile Include="Program.fs" />
    <PackageReference Include="Fable.Core" />
    <PackageReference Include="Fable.Browser.Dom" />
    <PackageReference Include="Fable.Browser.WebGL" />
  </ItemGroup>
  <Target Name="PrepareCandidateRuntimeSources" BeforeTargets="CoreCompile">
    <MakeDir Directories="_candidateSources" />
    <Copy SourceFiles="../CoreEnums.proposal.fs" DestinationFiles="_candidateSources/CoreEnums.proposal.fs" />
    <Copy SourceFiles="../StringEnums.proposal.fs" DestinationFiles="_candidateSources/StringEnums.proposal.fs" />
    <Copy SourceFiles="../BabylonBindings.generated.fs" DestinationFiles="_candidateSources/BabylonBindings.generated.fs" />
    <Copy SourceFiles="../BabylonGltf2Interface.generated.fs" DestinationFiles="_candidateSources/BabylonGltf2Interface.generated.fs" />
    <Copy SourceFiles="../BabylonLoadersBindings.generated.fs" DestinationFiles="_candidateSources/BabylonLoadersBindings.generated.fs" />
  </Target>
</Project>
