module FlowBlockMismatch
open BabylonjsBindings.SimpleClasses
open BabylonjsBindings.SimpleInterfaces
open BabylonjsBindings.FiniteDependentMaps
let mismatch (config: IFlowGraphGetAssetBlockConfiguration<FlowGraphMeshAsset>) : FlowGraphGetAssetBlock<FlowGraphAnimationAsset, Animation> = FlowGraphGetAssetBlock.Create config
