<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>netstandard2.1</TargetFramework><PackageId>BabylonjsBindings</PackageId><Version>0.1.3</Version><GeneratePackageOnBuild>true</GeneratePackageOnBuild><FablePackageType>library</FablePackageType><PackageTags>fable-javascript;babylon;bindings</PackageTags><PackageReadmeFile>README.md</PackageReadmeFile><RepositoryUrl>https://github.com/EHotwagner/BabylonjsBindings-full</RepositoryUrl><RepositoryType>git</RepositoryType><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile></PropertyGroup>
  <ItemGroup><Compile Include="Enums.fs" /><Compile Include="StringEnums.fs" /><Compile Include="ObjectTypes.fs" /><Compile Include="SimpleTypes.fs" /><Compile Include="M2FiniteDependentMaps.fs" /><Compile Include="SimpleFunctions.fs" /><Compile Include="SimpleVariables.fs" /><Compile Include="Bindings.fs" /></ItemGroup>
  <ItemGroup><PackageReference Include="Fable.Core" /><PackageReference Include="Fable.Package.SDK" /><PackageReference Include="Fable.Browser.Dom" /><PackageReference Include="Fable.Browser.WebGL" /><None Include="README.md" Pack="true" PackagePath="\" /></ItemGroup>
</Project>
